name: python-build-pr

on:
  pull_request:
    branches:
    - master

jobs:
  run_flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64' 
    - run: pip3 install -r requirements.txt
    - run: flake8 server/

  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64' 
    - run: pip3 install -r requirements.txt

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64' 
    - run: pip install -r requirements.txt